import Head from "next/head";
import CryptoGraph from "../components/CyptoGraph/CryptoGraph";
import FeaturesSection from "../components/Features/FeaturesSection";
import Header from "../components/Header/Header";
import Navigation from "../components/Navigation/Navigation";
import ProductSection from "../components/Product/ProductSection";
import Product from "../components/Product/ProductSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Project 53</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="font-Montserrat">
        <Navigation />
        <Header />
        <FeaturesSection />
        <ProductSection />
        <CryptoGraph />
      </section>
    </div>
  );
}
